### ISSUE TITLE
Refactor ReactJS code to comply with coding standard

### ISSUE THREAD

**Issue by marek-stopka** [PERLUR/BUSINESSstack#11]
Refactor ReactJS to comply with a [coding standard described by AirBnB](https://github.com/airbnb/javascript/tree/master/react).

**Comment by jan-mikulka** [comment]
@marek-stopka rules have been implemented, run `eslint resources/assets/js/*` to see unresolved rules.

note thet eslint package(s) might require to be installed globally on your operating system

**Comment by marek-stopka** [comment]
@jan-mikulka, thank you, your PR #13 has been merged into master.
